[build-system]
requires = ["setuptools>=43.0.0", "wheel>=0.36.2"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-extras = ["test"]
test-command = "pytest"

[pytest]
path = "tests"

[tool.pytest.ini_options]
enable_assertion_pass_hook = true
filterwarnings = ["ignore::DeprecationWarning:.*:"]
addopts = "--ignore=test/data"

[tool.bumpver]
current_version = "1.6.16"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"doc-source/conf.py" = ['release = "{version}"']
"tree_sitter_talon/core.py" = ['__version__: str = "{version}"']
