[build-system]
requires = ["setuptools>=43.0.0", "wheel>=0.36.2"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_24"
manylinux-i686-image = "manylinux_2_24"
manylinux-aarch64-image = "manylinux_2_24"
manylinux-ppc64le-image = "manylinux_2_24"
manylinux-s390x-image = "manylinux_2_24"
manylinux-pypy_x86_64-image = "manylinux_2_24"
manylinux-pypy_i686-image = "manylinux_2_24"
manylinux-pypy_aarch64-image = "manylinux_2_24"

[pytest]
path = "tests"

[tool.pytest.ini_options]
enable_assertion_pass_hook = true
filterwarnings = ["ignore::DeprecationWarning:.*:"]
addopts = "--ignore=test/data"

[tool.bumpver]
current_version = "4.0"
version_pattern = "MAJOR.MINOR"
commit_message = "Bump binding version {old_version} -> {new_version}"
commit = true
tag = false
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"']
"tree_sitter_talon/version.py" = ['__version_binding__: str = "{version}"$']

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39,py310
isolated_build = True

[testenv]
wheel=true
allowlist_externals = make
commands = make test
deps =
  pytest >=7.1.2, <8
  pytest-golden >=0.2.2, <0.3
"""
