name: Build & Test

on:
  push:
    branches:
      - dev
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
        experimental: [false]
        include:
          - # Earliest supported version:
            os: ubuntu-latest
            python-version: "3.9.8"
          - # Upcoming release candidate:
            os: ubuntu-latest
            python-version: "3.11.0-alpha - 3.11.0"
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions tox-poetry

      - name: Build & Test
        run: tox

  build-doc:
    name: Build Doc
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-doc.yml

  build-wheel:
    name: Build Wheel
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-wheel.yml

  release:
    name: Release
    needs: [build, build-doc, build-wheel]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
