name: Build wheel

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        python_tag: ["cp39", "cp310", "cp311"]
        os_and_platform_tag:
          - [ubuntu-latest, manylinux_x86_64]
          - [ubuntu-latest, manylinux_i686]
          - [ubuntu-latest, manylinux_aarch64]
          - [ubuntu-latest, manylinux_ppc64le]
          - [ubuntu-latest, manylinux_s390x]
          - [macos-latest, macosx_x86_64]
          - [macos-latest, macosx_universal2]
          - [macos-latest, macosx_arm64]
          - [windows-latest, win_amd64]
          - [windows-latest, win32]

    name: Build wheel for ${{ matrix.python_tag }}-${{ matrix.os_and_platform_tag[1] }}
    runs-on: ${{ matrix.os_and_platform_tag[0] }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "^3.9.8"
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.9.0
        with:
          output-dir: dist
        env:
          CIBW_BUILD: ${{ matrix.python_tag }}-${{ matrix.os_and_platform_tag[1] }}

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.whl
          if-no-files-found: error
