name: Build & Test

on:
  push:
    branches:
      - dev
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, macos-12, windows-2019, windows-2022]
        python-version: ["3.9"]
        experimental: [false]
        include:
          - os: ubuntu-latest
            python-version: "3.9.8"
            experimental: true
          - os: ubuntu-latest
            python-version: "3.9.9"
            experimental: true
          - os: ubuntu-latest
            python-version: "3.9.10"
            experimental: true
          - os: ubuntu-latest
            python-version: "3.9.11"
            experimental: true
          - os: ubuntu-latest
            python-version: "3.9.12"
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build & Test
        run: |
          poetry install --no-root --with ci
          poetry run tox --skip-missing-interpreters

      - name: Build SDist & Wheel
        if: matrix.experimental == false
        run: |
          poetry run cibuildwheel --output-dir dist
          poetry build --format=sdist
        env:
          CIBW_SKIP: pp* cp36* cp37* cp38* *musllinux*

      - name: Upload sdist
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: dist/**.tar.gz

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: dist/**.whl

  build-doc:
    name: Build Doc
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-doc.yml

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
