name: Build & Test

on:
  push:
    branches:
      - dev
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build & Test
        run: |
          poetry install -no-root --with ci
          poetry run tox --skip-missing-interpreters

  # build-wheel:
  #   name: Build Wheel
  #   needs: [build]
  #   if: github.event_name == 'push'
  #   uses: ./.github/workflows/build-wheel.yml

  build-doc:
    name: Build Doc
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-doc.yml

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
