name: build

on:
  push:
    branches:
      - dev
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        experimental: [false]
        include:
          - # Earliest supported version:
            os: ubuntu-20.04
            python-version: "3.7.1"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt

      - name: Build & Test
        run: pipx run --spec tox==4.4.6 tox

  build-doc:
    name: Build Doc
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-doc.yml

  build-sdist:
    name: Build sdist
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-sdist.yml

  build-wheel:
    name: Build wheel
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-wheel.yml

  release:
    name: Release
    needs: [build, build-doc, build-sdist, build-wheel]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
