name: Build Doc

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-doc:
    name: Build Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "^3.9.8"
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt

      - name: Build Doc
        run: |
          poetry install -E docs
          poetry run sphinx-build -M "html" "docs" "docs/_build"

      - name: Deploy Doc
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: docs
          folder: docs/_build/html
