name: build doc

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-doc:
    name: Build doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "^3.9.8"
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt

      - name: Build doc
        run: |
          pipx run --spec poetry==1.4.0 \
            poetry install  --without dev --with docs
          pipx run --spec poetry==1.4.0 \
            poetry run sphinx-build -M "html" "docs" "docs/_build"

      - name: Deploy doc
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: docs
          folder: docs/_build/html
