name: Build & Test

on:
  push:
    branches:
      - dev
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
        build-format: ["wheel"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build & Test
        run: |
          poetry install --no-root --with ci
          poetry run tox --skip-missing-interpreters
          poetry run cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: pp* cp36* cp37* cp38* *musllinux*

      - name: Upload wheel
        if: ${{ matrix.build-format }} == 'wheel'
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: dist/**.whl

  build-doc:
    name: Build Doc
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-doc.yml

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
