name: CI

on: [push]

jobs:
  test:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install .[test,publish]
      - run: pytest
      - run: stubtest --mypy-config-file pyproject.toml tree_sitter_talon
      - run: make run/dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true

  sphinx:
    name: Publish API Documentation
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install .[sphinx]
      - run: make html
      - uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: docs
          folder: _build/html
