name: CI

on: [push]

defaults:
  run:
    shell: bash

env:
  RECOMMENDED_OS: "Linux"
  RECOMMENDED_PYTHON_VERSION: "3.9"

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      ################################################################################
      # Setup
      ################################################################################
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-dev.txt"
      - run: pip install .[test,sphinx,publish]

      ################################################################################
      # Test
      ################################################################################
      - name: Run PyTest
        run: pytest
      - name: Run MyPy Stubtest
        run: stubtest --mypy-config-file pyproject.toml tree_sitter_talon

      ################################################################################
      # Dynamic Library: Build & Publish
      ################################################################################
      - name: Build library
        run: |
          python -c 'import tree_sitter_talon;print(f"LIBPATH={tree_sitter_talon.library_path}")' >> $GITHUB_ENV
          python -c 'import tree_sitter_talon;print(f"LIBNAME={tree_sitter_talon.library_name}")' >> $GITHUB_ENV
      - name: Upload library
        if: matrix.python-version == env.RECOMMENDED_PYTHON_VERSION && startsWith(github.ref, 'refs/tags')
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.LIBNAME }}
          path: ${{ env.LIBPATH }}

      ################################################################################
      # Sphinx Doc: Build & Publish
      ################################################################################
      - name: Build Sphinx Doc
        run: make html
      - name: Publish Sphinx Doc
        if: matrix.python-version == env.RECOMMENDED_PYTHON_VERSION && runner.os == env.RECOMMENDED_OS
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: docs
          folder: _build/html

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      ################################################################################
      # Setup
      ################################################################################
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.RECOMMENDED_PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: "requirements-dev.txt"
      - run: pip install .[test,sphinx,publish]

      ################################################################################
      # Build
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        run: python -m build

      ################################################################################
      # Publish to PyPi
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        run: |
          twine check dist/*
          twine upload --skip-existing -r pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      ################################################################################
      # Publish to GitHub Release
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        uses: actions/download-artifact@v3
        with:
          path: dist

      - run: ls -R

      - if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
            dist/**/tree_sitter_talon-*.so
            dist/**/tree_sitter_talon-*.dylib
            dist/**/tree_sitter_talon-*.dll
          fail_on_unmatched_files: true
