name: CI

on: [push]

defaults:
  run:
    shell: bash

env:
  RECOMMENDED_OS: "Linux"
  RECOMMENDED_PYTHON_VERSION: "3.9"

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      ################################################################################
      # Setup
      ################################################################################
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            requirements-doc.txt
            requirements-test.txt
      - run: pip install .[dev,doc,test]
      ################################################################################
      # Test
      ################################################################################
      - run: python setup.py pytest
      - run: stubtest --mypy-config-file pyproject.toml tree_sitter_talon

      ################################################################################
      # Build Wheels
      ################################################################################
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        env:
          CIBW_SKIP: cp36-* cp37-* cp38-* *musllinux*
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./wheelhouse/*.whl

      ################################################################################
      # Build API Documentation
      ################################################################################
      - name: Build Sphinx Doc
        run: make html
      - name: Publish Sphinx Doc
        if: matrix.python-version == env.RECOMMENDED_PYTHON_VERSION && runner.os == env.RECOMMENDED_OS
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: docs
          folder: _build/html

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      ################################################################################
      # Setup
      ################################################################################
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.RECOMMENDED_PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            requirements-doc.txt
            requirements-test.txt
      - run: pip install .[dev,doc,test]
      ################################################################################
      # Build Source Distribution
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        run: python -m build --sdist

      ################################################################################
      # Download Wheels
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      ################################################################################
      # Publish to PyPi
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        run: |
          twine check dist/**.tar.gz dist/**.whl
          twine upload --skip-existing -r pypi dist/**.tar.gz dist/**.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      ################################################################################
      # Publish to GitHub Release
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**.whl
            dist/**.tar.gz
          fail_on_unmatched_files: true
