name: CI

on:
  push:
    branches:
      - dev
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:

defaults:
  run:
    shell: sh

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [tox, sdist, cibuildwheel]
    uses: ./.github/workflows/release.yml
