name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install .[test]
      - run: pytest
      - run: stubtest --mypy-config-file pyproject.toml tree_sitter_talon
      - run: |
          python -c '\
            import platform;\
            ext={"Linux":"so","Darwin":"dylib","Windows":"dll"}[platform.system()];\
            print(f"TALON_LIBRARY_NAME=talon-{platform.python_version()}-{platform.machine()}.{ext}")\
            ' >> $GITHUB_ENV

  sphinx:
    name: Sphinx
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install .[sphinx]
      - run: make html
      - uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: docs
          folder: _build/html
