name: Publish

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - uses: Gr1N/setup-poetry@v7

      - name: Build Sphinx Doc
        run: |
          poetry build
          poetry run sphinx-build -M "html" "docs" "docs/_build"

      - name: Publish Sphinx Doc
        if: matrix.python-version == env.RECOMMENDED_PYTHON_VERSION && runner.os == env.RECOMMENDED_OS
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: docs
          folder: docs/_build/html
