name: release

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: sh

env:
  # NOTE: The default Python version is installed with actions/setup-python.
  DEFAULT_PYTHON_VERSION: "3.11"

jobs:
  ################################################################################
  # Publish docs to GitHub Pages
  ################################################################################

  docs:
    strategy:
      matrix:
        os:
          - name: "Linux"
            type: "ubuntu-latest"

    name: docs / ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.type }}

    steps:
      - name: Get source
        uses: actions/checkout@v3
        with:
          submodules: true

      - # Required to run job via act: https://github.com/nektos/act
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: "./pyproject.toml"
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Setup dependencies
        run: pip install .[docs]

      - name: Build docs
        run: sphinx-build -M 'html' 'docs' 'docs/_build'"

      - name: Deploy doc
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: docs
          folder: docs/_build/html

  ################################################################################
  # Publish package to GitHub Releases
  ################################################################################

  github:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
          fail_on_unmatched_files: true

  ################################################################################
  # Publish package to PyPI
  ################################################################################

  pypi:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/tree-sitter-talon

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
