name: Release

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      # - name: Publish to PyPi
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      #     skip_existing: true

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**.tar.gz
            dist/**.whl
          fail_on_unmatched_files: true
